import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../core/ephemeris.dart';

class PdfService {
  /// Generates a PDF Astrological Report and opens the system share dialog
  Future<void> generateAndShareAstrologicalReport(ChartData chartData, String name, DateTime date) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            pw.Header(
              level: 0,
              child: pw.Center(
                child: pw.Text('Jyotish Cosmic Report', style: pw.TextStyle(fontSize: 28, fontWeight: pw.FontWeight.bold, color: PdfColors.deepPurple800)),
              ),
            ),
            pw.SizedBox(height: 20),
            pw.Text('Name: $name', style: pw.TextStyle(fontSize: 18)),
            pw.Text('Date of Birth: ${date.toIso8601String().split('T')[0]}', style: pw.TextStyle(fontSize: 18)),
            pw.SizedBox(height: 20),
            pw.Divider(),
            pw.SizedBox(height: 20),
            pw.Text('Planetary Positions', style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold, color: PdfColors.deepPurple600)),
            pw.SizedBox(height: 10),
            _buildPlanetsTable(chartData),
            pw.SizedBox(height: 40),
            pw.Center(
              child: pw.Text('Generated by Mobile Jyotish', style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey)),
            )
          ];
        },
      ),
    );

    final Uint8List bytes = await pdf.save();
    await Printing.sharePdf(bytes: bytes, filename: '${name.replaceAll(' ', '_')}_Jyotish_Report.pdf');
  }

  pw.Widget _buildPlanetsTable(ChartData chartData) {
    final List<List<String>> tableData = [
      ['Planet/Point', 'Longitude'],
    ];

    tableData.add(['Ascendant', '${chartData.ascendantSidereal.toStringAsFixed(2)}°']);
    
    chartData.planetLongitudes.forEach((planet, degree) {
      tableData.add([planet.toUpperCase(), '${degree.toStringAsFixed(2)}°']);
    });

    return pw.TableHelper.fromTextArray(
      headers: tableData.first,
      data: tableData.sublist(1),
      headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
      headerDecoration: const pw.BoxDecoration(color: PdfColors.deepPurple),
      cellHeight: 30,
      cellAlignments: {
        0: pw.Alignment.centerLeft,
        1: pw.Alignment.centerRight,
      },
    );
  }
}
